name: beta-diversity-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=1.3
  - numpy>=1.21
  - matplotlib>=3.4
  - seaborn>=0.11
  - scikit-bio>=0.5.6
  - scikit-learn>=1.0
  - statsmodels>=0.13
  - pip
  - pip:
      - openpyxl  # If using .xlsx files
